// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvetmzburjgeseseqqwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2ZXRtemJ1cmpnZXNlc2VxcXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTc1NzAsImV4cCI6MjA3MDc3MzU3MH0.dez7bY_6xVaAWT46tq-05BUlB7Ds-tQr63j6nK2Pjkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    redirectTo: 'https://alytix.in/auth/callback',  // Added custom domain redirect
  }
});
